### PR TITLE
Remove subler (add Crossplatform support)

### PR DESCRIPTION
**Pull request by jvanbruegge**
I removed subler from the tagging fuctions so the code works with non-Mac machines. I tested the whole stuff on Linux and it worked flawless with iTunes.
The subler file is still there to support the optimize flag.
The library that is used is completely written in Python so it should work on all platforms.

### CODE REVIEW

**Comment by ccjensen** [comment]
Hey,

Thanks for the pull request. I invoked PlexMediaTagger with the exact invocation with current master and then once again with your tool on a copy of the same video file. Seeing quite a few difference in what tags got added and their values:
screen shot 2015-07-22 at 20 20 38
was this intentional?

and I also saw an '8' get logged:

       processing 1/1 part_items
       tagging...
       8
       Finding '/Volumes/Drobo/TV/Psych/Psych - Season 8/Psych - S08E01 - Lock, Stock, Some Smoking Barrels and Burton Guster's Goblet of Fire.m4v' in iTunes...
any ideas on what that could be?

**Comment by SuperManitu** [comment]
oh, yeah, I didn't used all tags (like disk number, etc) I'll add them
The 8 could be a leftover from my debugging, will fix that too

**Comment by ccjensen** [comment]
cool, thanks!
I'm very interested in this change, and if it can match the capabilities of the current code I'd be more than happy to merge it in!

**Comment by ccjensen** [comment]
still interested in this if you'd like to get it cleaned up and ready to be merged!

**Comment by jvanbruegge** [comment]
Yeah, will do this in the next few days

**Comment by ccjensen** [comment]
just noticed this was sitting here idle. Is this something that you are still pursuing?

**Comment by jvanbruegge** [comment]
Not really, I am not using plex any more and the code here is horrible, from where I was just starting out with programming

**Pull request closed without merging**
